# Generated by Django 3.0.2 on 2020-02-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prot',
            name='image',
            field=models.ImageField(default='default.png', upload_to='./image'),
        ),
        migrations.AlterField(
            model_name='prot',
            name='description',
            field=models.CharField(default='在这里写作品简介', max_length=100),
        ),
    ]
